FROM golang:1.14-alpine as builder

RUN apk update && apk add gcc libc-dev git

WORKDIR /app/compass

COPY ./go.mod .
COPY ./go.sum .

COPY . .

RUN chmod a+rx ./test/build-plugins.test.sh
RUN sh ./test/build-plugins.test.sh

CMD CGO_ENABLED=0 go test -v -coverpkg ./... ./...

